name: 'Build all Azure AD B2C custom policies'
description: 'A GitHub Action for building all Azure AD B2C policies using the appsettings.json utilized by the VSCode extension'
author: 'Carsten Blume'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  policyFolder:
    description: 'The folder where the custom policies files and appsettings.json are stored'
    required: true
  outputFolder:
    description: 'The folder where the built policy files will be stored in a subfolder for each environment'
    required: true
  renumberSteps:
    description: 'Renumber the orchestration steps. Possible values: true, or false'
    required: false
    default: 'false'
  verbose:
    description: 'Log level verbose.'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'